name: morphic-8
recipe: pantheon
config:
  framework: drupal8
  site: morphic-8
  id: e1be4569-558f-4870-87f6-c193dba1ea23
  php: '7.1'
services:
  node:
    type: 'node:6.10'
    run:
      - cd $LANDO_MOUNT/themes/custom/morphic && npm install
      - cd $LANDO_MOUNT/themes/custom/morphic && gulp
    overrides:
      services:
        ports:
          - '3003:3003'
    globals:
      gulp: latest
      bower: latest
      npm: latest
tooling:
  gulp:
    service: node
  bower:
    service: node
  npm:
    service: node
  node:
    service: node
